export const GET_CURRENCIES = "GET_CURRENCIES";
export const ADD_CURRENCIES = "ADD_CURRENCIES";
export const EDIT_CURRENCIES = "EDIT_CURRENCIES";
export const DELETE_CURRENCIES = "DELETE_CURRENCIES";
